### ISSUE TITLE
How to install LCD driver JD9366

### ISSUE THREAD

**Issue by metaboonma** [cutiepi-io/cutiepi-drivers#1]
I'm wondering if I can get to the kernel source directory. How to build the module?
[](https://github.com/cutiepi-io/cutiepi-drivers#mipi-display)

![image](https://user-images.githubusercontent.com/30387155/80119242-a3162880-85b3-11ea-9e54-930881c8b81c.png)

Can you tell me the installation steps in this section?

**Comment by penk** [comment]
Hi @metaboonma, we used [rpi-source](https://github.com/notro/rpi-source/wiki) to obtain kernel source, and `make -C . M=drivers/gpu/drm/panel/` to rebuild the driver.

**Comment by metaboonma** [comment]
Hi  @penk 
Can you help me fix a Rpi-Source installation error? As the picture?

![image](https://user-images.githubusercontent.com/30387155/80202896-80861d00-8650-11ea-96f1-573f92332fb3.png)

**Comment by penk** [comment]
@metaboonma the error is literally written in the screenshot, you failed to install needed package because of network issue.

**Comment by metaboonma** [comment]
Hi @penk 
Thanks for your answer I have another question to ask you.

Do I have to run the 'make menuconfig' command to make settings?
![image](https://user-images.githubusercontent.com/30387155/80333243-96c1f200-8877-11ea-8659-d3ce69c193e1.png)

If I have to set up, what are the settings?
![image](https://user-images.githubusercontent.com/30387155/80333417-2ebfdb80-8878-11ea-8f1a-21080208ae56.png)

The next question is I have to copy all the files under the folder Display/drivers/gpu/drm/panel/ to /home/pi/linux/drivers/gpu/drm/panel'  As the picture?
![image](https://user-images.githubusercontent.com/30387155/80333896-c671f980-8879-11ea-8cd0-3099c02477ef.png)

And what to do next.

**Comment by penk** [comment]
@metaboonma Sorry, but this is not the right place to discuss, since it's not an issue for the driver, and this isn't an online forum. 

I would suggest you to learn some basic kernel configuring and building knowledge before trying. 
If you do have an issue with the driver itself, you may reach me via email: penk@cutiepi.io. Good luck.

**Comment by metaboonma** [comment]
Please help me. 
I tried to build, but there was an error as shown in the picture. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/30387155/80575028-15ac5b80-8a2d-11ea-8bd6-ee98251fa87d.png)

**Comment by metaboonma** [comment]
Hello penk,and Happy new year 2021
I have something for you to help.
I tried installing The full raspbian-cutiepi from
https://github.com/cutiepi-io/cutiepi-shell/releases. But the display is
split Side-by-Side clone screen , how to fix it?
[image: image.png]

 I used rpi-source to get the source kernel, and install the screen drivers
as per your suggestion last year it was showing the same.

[image: image.png]
Can you help me please.

--

Best Regards,

Meta Boonma
Mobile: (+66) 8 2784 0134
Email: metasound00@gmail.com

ในวันที่ จ. 27 เม.ย. 2020 เวลา 12:18 penk <notifications@github.com>
เขียนว่า:
